import { Router } from 'express';
import authRoutes from './auth.routes.js';
import categoriesRoutes from './categories.routes.js';
import productsRoutes from './products.routes.js';
import ordersRoutes from './orders.routes.js';
import customersRoutes from './customers.routes.js';
import inventoryRoutes, { ingredientsRouter } from './inventory.routes.js';
import recipesRoutes from './recipes.routes.js';
import employeesRoutes, { schedulesRouter, attendanceRouter, leavesRouter, payrollRouter } from './employees.routes.js';
import reportsRoutes from './reports.routes.js';
import productionRoutes from './production.routes.js';
import salesRoutes from './sales.routes.js';
import usersRoutes from './users.routes.js';
import settingsRoutes from './settings.routes.js';
import cashRegisterRoutes from './cash-register.routes.js';
import { caisseRouter, suppliersRouter, expenseCategoriesRouter, revenueCategoriesRouter, invoicesRouter, paymentsRouter } from './accounting.routes.js';
import returnRoutes from './return.routes.js';
import storeRoutes from './store.routes.js';
import uploadRoutes from './upload.routes.js';
import notificationsRoutes from './notifications.routes.js';
import purchaseOrderRoutes from './purchase-order.routes.js';
import receptionVoucherRoutes from './reception-voucher.routes.js';
import replenishmentRoutes from './replenishment.routes.js';
import productLossRoutes from './product-loss.routes.js';
import ingredientLotRoutes from './ingredient-lot.routes.js';
import purchaseRequestRoutes from './purchase-request.routes.js';
import referentielRoutes from './referentiel.routes.js';
import productPipelineRoutes from './product-pipeline.routes.js';
import unsoldDecisionRoutes from './unsold-decision.routes.js';
import productionContenantRoutes from './production-contenant.routes.js';
import stockFrigoRoutes from './stock-frigo.routes.js';
import bonSortieRoutes from './bon-sortie.routes.js';
import productionEtapesRoutes from './production-etapes.routes.js';
import productionCoutRoutes from './production-cout.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/categories', categoriesRoutes);
router.use('/products', productsRoutes);
router.use('/orders', ordersRoutes);
router.use('/customers', customersRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/ingredients', ingredientsRouter);
router.use('/recipes', recipesRoutes);
router.use('/employees', employeesRoutes);
router.use('/schedules', schedulesRouter);
router.use('/attendance', attendanceRouter);
router.use('/leaves', leavesRouter);
router.use('/payroll', payrollRouter);
router.use('/reports', reportsRoutes);
router.use('/production', productionRoutes);
router.use('/sales', salesRoutes);
router.use('/settings', settingsRoutes);
router.use('/cash-register', cashRegisterRoutes);
router.use('/caisse', caisseRouter);
router.use('/suppliers', suppliersRouter);
router.use('/expense-categories', expenseCategoriesRouter);
router.use('/revenue-categories', revenueCategoriesRouter);
router.use('/invoices', invoicesRouter);
router.use('/payments', paymentsRouter);
router.use('/returns', returnRoutes);
router.use('/stores', storeRoutes);
router.use('/upload', uploadRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/purchase-orders', purchaseOrderRoutes);
router.use('/reception-vouchers', receptionVoucherRoutes);
router.use('/replenishment', replenishmentRoutes);
router.use('/product-losses', productLossRoutes);
router.use('/ingredient-lots', ingredientLotRoutes);
router.use('/purchase-requests', purchaseRequestRoutes);
router.use('/params', referentielRoutes);
router.use('/product-pipeline', productPipelineRoutes);
router.use('/unsold-decisions', unsoldDecisionRoutes);
router.use('/contenants', productionContenantRoutes);
router.use('/stock-frigo', stockFrigoRoutes);
router.use('/bons-sortie', bonSortieRoutes);
router.use('/production-etapes', productionEtapesRoutes);
router.use('/production-cout', productionCoutRoutes);

export default router;
