-- Add CIMR support
ALTER TABLE payroll ADD COLUMN IF NOT EXISTS cimr_employee DECIMAL(12,2) DEFAULT 0;
ALTER TABLE payroll ADD COLUMN IF NOT EXISTS cimr_employer DECIMAL(12,2) DEFAULT 0;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS cimr_rate DECIMAL(5,2) DEFAULT 0;
