-- Theme / Appearance settings
ALTER TABLE company_settings
  ADD COLUMN IF NOT EXISTS theme_bg_page       VARCHAR(7) DEFAULT '#FAF6F1',
  ADD COLUMN IF NOT EXISTS theme_bg_card       VARCHAR(7) DEFAULT '#FFFDF9',
  ADD COLUMN IF NOT EXISTS theme_bg_secondary  VARCHAR(7) DEFAULT '#F3ECE2',
  ADD COLUMN IF NOT EXISTS theme_bg_separator  VARCHAR(7) DEFAULT '#E8DDD0',
  ADD COLUMN IF NOT EXISTS theme_text_strong   VARCHAR(7) DEFAULT '#2D1810',
  ADD COLUMN IF NOT EXISTS theme_text_body     VARCHAR(7) DEFAULT '#5C3D2E',
  ADD COLUMN IF NOT EXISTS theme_text_muted    VARCHAR(7) DEFAULT '#8B7355',
  ADD COLUMN IF NOT EXISTS theme_accent        VARCHAR(7) DEFAULT '#C4872B',
  ADD COLUMN IF NOT EXISTS theme_accent_hover  VARCHAR(7) DEFAULT '#A8721F',
  ADD COLUMN IF NOT EXISTS theme_accent_light  VARCHAR(7) DEFAULT '#F5E6CC',
  ADD COLUMN IF NOT EXISTS theme_cta_color     VARCHAR(7) DEFAULT '#C4872B',
  ADD COLUMN IF NOT EXISTS theme_cta_text      VARCHAR(7) DEFAULT '#FFFFFF';
