-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 128 : Import des produits depuis Book2.xlsx + vente au poids
--
-- Apporte :
--   1. products.sale_unit + products.price_per_kg (vente au poids)
--   2. sale_items.unit (distingue ligne unitaire vs ligne au poids en grammes)
--   3. 5 nouvelles catégories (Baguettes, Beldi, Salée, Les boîtes, Plateaux)
--   4. 236 produits unitaires + 35 produits-famille au poids
--
-- Pour les produits au poids (sale_unit='weight'), la ligne de vente stocke
-- le poids en grammes dans sale_items.quantity et sale_items.unit='g'. Le
-- prix unitaire affiché est le prix/kg, le subtotal vaut quantity/1000 * price.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- ─── 1. Vente au poids sur products ───
ALTER TABLE products ADD COLUMN IF NOT EXISTS sale_unit VARCHAR(10) NOT NULL DEFAULT 'unit';
ALTER TABLE products ADD COLUMN IF NOT EXISTS price_per_kg DECIMAL(10,2);
DO $$ BEGIN
  ALTER TABLE products ADD CONSTRAINT products_sale_unit_check CHECK (sale_unit IN ('unit', 'weight'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ─── 1bis. Vente au poids sur sale_items ───
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS unit VARCHAR(10) NOT NULL DEFAULT 'unit';
DO $$ BEGIN
  ALTER TABLE sale_items ADD CONSTRAINT sale_items_unit_check CHECK (unit IN ('unit', 'g'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ─── 2. Nouvelles catégories (DLC/DLV par défaut alignés avec migration 061) ───
INSERT INTO categories (name, slug, description, display_order) VALUES ('Baguettes', 'baguettes', 'Baguettes classiques et tradition', 2) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, description, display_order) VALUES ('Beldi', 'beldi', 'Pâtisseries beldi (cornes de gazelle, ghriba, fekkas, halwat...)', 7) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, description, display_order) VALUES ('Salée', 'salee', 'Produits salés (pizzas, quiches, msemen, briouates, pastilla...)', 8) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, description, display_order) VALUES ('Les boîtes', 'les-boites', 'Boîtes garnies, sablés prestige, mini cookies, financiers...', 9) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, description, display_order) VALUES ('Plateaux', 'plateaux', 'Plateaux soirée, mixte, beldi, sablé, prestige...', 10) ON CONFLICT (slug) DO NOTHING;

-- ─── 3. DLC/DLV par défaut pour les nouvelles catégories (UPDATE après INSERT produits) ───
-- (sera appliqué après insertion des produits via les colonnes individuelles)

-- ─── 4. Insertion 271 produits ───

-- Helper CTE pour récupérer les IDs catégories
WITH cat_lookup AS (
  SELECT id, slug FROM categories
)
INSERT INTO products (
  name, slug, category_id, description, price, cost_price,
  is_available, is_custom_orderable, shelf_life_days, display_life_hours,
  sale_type, sale_unit, price_per_kg, stock_quantity, stock_min_threshold
) VALUES
  ('AMANDINE', 'amandine', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 18.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('AMANDINE 6 PERSONNES', 'amandine-6-personnes', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 170.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('AMANDINE 8 PERSONNES', 'amandine-8-personnes', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 250.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('BAGUETTE À L''ANCIENNE', 'baguette-a-l-ancienne', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 5.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('BAGUETTE COMPLÈTE', 'baguette-complete', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 3.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('BAGUETTE NORMALE FARINE', 'baguette-normale-farine', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 1.5, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('BAGUETTE NORMALE SÉSAME', 'baguette-normale-sesame', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 2.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('BAGUETTE NORMALE', 'baguette-normale', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 1.5, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('BAGUETTE SEMOULE', 'baguette-semoule', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 3.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('BAGUETTE TRADITION CÉRÉALE', 'baguette-tradition-cereale', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 6.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('BAGUETTE TRADITION OLIVE', 'baguette-tradition-olive', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 6.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('BAGUETTE TRADITION PAVOT', 'baguette-tradition-pavot', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 6.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('BAGUETTE TRADITION SÉSAME', 'baguette-tradition-sesame', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 6.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('BAGHRIR 10 PIÈCES', 'baghrir-10-pieces', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 10.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'unit', NULL, 0, 0),
  ('BAGUETTE AVOINE (CHOFANE)', 'baguette-avoine-chofane', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 6.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('BAGUETTE NORMALE 1,25', 'baguette-normale-1-25', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 1.25, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('BAGUETTE SUCRÉE', 'baguette-sucree', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 4.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('BASBOUSA', 'basbousa', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 5.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('BASBOUSA CRÈME', 'basbousa-creme', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('BATBOUT', 'batbout', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 5.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'unit', NULL, 0, 0),
  ('BATBOUT MINI', 'batbout-mini', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 3.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('BEBE BATBOUT 10 PIÈCES', 'bebe-batbout-10-pieces', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 10.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('BEBE BATBOUT 1 PIECE', 'bebe-batbout-1-piece', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 1.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('BEBE MSEMEN FARCI VIANDE', 'bebe-msemen-farci-viande', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 8.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('BEBE SANDWICH COMPLÈTE', 'bebe-sandwich-complete', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 12.5, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('BEIGNETS', 'beignets', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 5.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('BEIGNETS CHOCOLAT/CITRON/FRAMBOISE', 'beignets-chocolat-citron-framboise', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 6.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('BOÎTE SALÉE', 'boite-salee', (SELECT id FROM cat_lookup WHERE slug = 'les-boites'), NULL, 25.0, NULL, TRUE, FALSE, 60, 360, 'dlv', 'unit', NULL, 0, 0),
  ('BOSTOCK AMANDE', 'bostock-amande', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 5.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('BRIOCHE', 'brioche', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 4.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('BRIOUATE VIANDE HACHÉE', 'briouate-viande-hachee', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 5.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('BRIOUATE POULET', 'briouate-poulet', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('BROWNIE', 'brownie', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 10.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('CAKE CAROTTE', 'cake-carotte', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 23.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('CAKE CHOCOLAT', 'cake-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 45.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('CAKE CITRON', 'cake-citron', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 45.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('CAKE DESIGN', 'cake-design', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 750.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('CAKE FRUITS SECS', 'cake-fruits-secs', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 45.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('CAKE NATURE', 'cake-nature', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 40.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('CAKE OREO', 'cake-oreo', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 23.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('CAKE ROCHER CHOCOLAT', 'cake-rocher-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 60.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('CAKE ROCHER FRAMBOISE', 'cake-rocher-framboise', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 60.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('CAKE ROCHER FRUITS SECS', 'cake-rocher-fruits-secs', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 60.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('CAKE ROCHER TRANCHE', 'cake-rocher-tranche', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 6.5, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('CASABLANCA', 'casablanca', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 15.5, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('CASABLANCA 10 PERSONNES', 'casablanca-10-personnes', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 300.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('CASABLANCA 6 PERSONNE', 'casablanca-6-personne', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 150.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('CASABLANCA 8 PERSONNES', 'casablanca-8-personnes', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 180.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('CHAHDA', 'chahda', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 15.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('CHAUSSON AUX POMMES', 'chausson-aux-pommes', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 6.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('CHEESECAKE CITRON', 'cheesecake-citron', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 17.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('CHEESECAKE FRAMBOISE', 'cheesecake-framboise', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 17.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('CHEESECAKE LOTUS', 'cheesecake-lotus', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 17.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('COOKIES CHOCOLAT', 'cookies-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 8.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('COOKIES FRAMBOISE', 'cookies-framboise', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 9.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('COOKIES PISTACHE', 'cookies-pistache', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 10.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('CROC MONSIEUR', 'croc-monsieur', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 22.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('CROC MONSIEUR MINI', 'croc-monsieur-mini', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 11.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('CROISSANT', 'croissant', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 5.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('CROISSANT AMÉRICAIN', 'croissant-americain', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 8.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('CROISSANT AU CHOCOLAT NOIR', 'croissant-au-chocolat-noir', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 6.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('CROISSANT BICOLORE CACAO', 'croissant-bicolore-cacao', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 6.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('CROISSANT COMPLÈTE', 'croissant-complete', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 6.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('CROISSANT SALÉE', 'croissant-salee', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 10.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('CRUNCHE CARAMEL', 'crunche-caramel', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 20.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('DANISH ABRICOT', 'danish-abricot', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 7.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('DANISH CHOCOLAT', 'danish-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 7.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('DANISH FRAMBOISE/CHOCOLAT', 'danish-framboise-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 7.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('DANISH FRUITS', 'danish-fruits', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 8.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('DIAMANTINE FROMAGE', 'diamantine-fromage', (SELECT id FROM cat_lookup WHERE slug = 'les-boites'), NULL, 25.0, NULL, TRUE, FALSE, 60, 360, 'dlv', 'unit', NULL, 0, 0),
  ('DIAMANTINE NATURE', 'diamantine-nature', (SELECT id FROM cat_lookup WHERE slug = 'les-boites'), NULL, 20.0, NULL, TRUE, FALSE, 60, 360, 'dlv', 'unit', NULL, 0, 0),
  ('ECLAIR CHOCOLAT', 'eclair-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 15.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('ECLAIR FRAMBOISE', 'eclair-framboise', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 15.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('ECLAIR VANILLE', 'eclair-vanille', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 13.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('ÉCLAIRE FRAISE', 'eclaire-fraise', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 12.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('FEKASS DENTELLE', 'fekass-dentelle', (SELECT id FROM cat_lookup WHERE slug = 'les-boites'), NULL, 35.0, NULL, TRUE, FALSE, 60, 360, 'dlv', 'unit', NULL, 0, 0),
  ('FEKKAS CRÈME', 'fekkas-creme', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 50.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'unit', NULL, 0, 0),
  ('FEUILLE 8 PERSONNES', 'feuille-8-personnes', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 150.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('FEUILLE D''AUTOMNE', 'feuille-d-automne', NULL, NULL, 19.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('FEUILLES D''AUTOMNE 8 PERSONNES', 'feuilles-d-automne-8-personnes', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 170.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('FEUILLETINE FROMAGE', 'feuilletine-fromage', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 37.5, NULL, TRUE, FALSE, 90, 360, 'dlv', 'unit', NULL, 0, 0),
  ('FINANCIER GRAND', 'financier-grand', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 7.5, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('FINANCIER MINI', 'financier-mini', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 3.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('FLAN VANILLE', 'flan-vanille', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 8.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('FORÊT NOIR', 'foret-noir', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 16.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('FOURRÉ AMANDE G', 'fourre-amande-g', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 8.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('FOURRÉ AMANDE/CHOCOLAT/CITRON', 'fourre-amande-chocolat-citron', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 4.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('FRAISIER', 'fraisier', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 15.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('FRAISIER 15 PERSONNES', 'fraisier-15-personnes', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 250.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('GÂTEAU FRUITS 8 PERSONNES', 'gateau-fruits-8-personnes', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 220.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('GÂTEAU O FAURIA 15 PERS', 'gateau-o-fauria-15-pers', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 400.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('GÂTEAUX FERRERO ROCHER 10 PIÈCES', 'gateaux-ferrero-rocher-10-pieces', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 350.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('GATEAUX MOELLEUX', 'gateaux-moelleux', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 0, NULL, TRUE, TRUE, 30, 72, 'commande', 'unit', NULL, 0, 0),
  ('GHRIBA NATURE', 'ghriba-nature', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 20.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'unit', NULL, 0, 0),
  ('HARCHA COMPLÈTE', 'harcha-complete', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 5.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('HARCHA KOUNAFA', 'harcha-kounafa', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 5.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('HARCHA ORGE', 'harcha-orge', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 4.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('HARCHA RAISIN', 'harcha-raisin', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 4.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('HARSHA', 'harsha', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 3.5, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('HARSHA FROMAGE', 'harsha-fromage', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 4.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('HARSHA OLIVE', 'harsha-olive', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 4.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('JALOUSIE ABRICOT', 'jalousie-abricot', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 5.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('JALOUSIE AUX AMANDES', 'jalousie-aux-amandes', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 8.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('JALOUSIE AUX POMMES', 'jalousie-aux-pommes', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 7.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('JALOUSIE ROND POMME', 'jalousie-rond-pomme', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 6.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('KOUNAFA CREME', 'kounafa-creme', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('LE RESTE DU COMMANDE GÂTEAU BELDI', 'le-reste-du-commande-gateau-beldi', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 830.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'unit', NULL, 0, 0),
  ('LE RESTE DU COMMANDE PLATEAU SOIRÉE G', 'le-reste-du-commande-plateau-soiree-g', (SELECT id FROM cat_lookup WHERE slug = 'plateaux'), NULL, 170.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('LE RESTE DU PLATEAU SOIRÉE G', 'le-reste-du-plateau-soiree-g', (SELECT id FROM cat_lookup WHERE slug = 'plateaux'), NULL, 230.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('LE RESTE DU PLATEAU VIENNOISERIES', 'le-reste-du-plateau-viennoiseries', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 180.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('MACARON', 'macaron', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 7.5, NULL, TRUE, FALSE, 30, 120, 'dlv', 'unit', NULL, 0, 0),
  ('MACARON 6 PS', 'macaron-6-ps', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 40.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('MACARON CHOCOLAT', 'macaron-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 7.5, NULL, TRUE, FALSE, 30, 120, 'dlv', 'unit', NULL, 0, 0),
  ('MACARON CITRON', 'macaron-citron', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 7.5, NULL, TRUE, FALSE, 30, 120, 'dlv', 'unit', NULL, 0, 0),
  ('MACARON FRAMBOISE', 'macaron-framboise', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 7.5, NULL, TRUE, FALSE, 30, 120, 'dlv', 'unit', NULL, 0, 0),
  ('MACARON PISTACHE', 'macaron-pistache', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 7.5, NULL, TRUE, FALSE, 30, 120, 'dlv', 'unit', NULL, 0, 0),
  ('MACARON VANILLE', 'macaron-vanille', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 7.5, NULL, TRUE, FALSE, 30, 120, 'dlv', 'unit', NULL, 0, 0),
  ('MADELEINE', 'madeleine', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 6.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MADELEINE CHOCOLAT', 'madeleine-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MADELEINE CITRON', 'madeleine-citron', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MILLE FEUILLE CHOCOLAT', 'mille-feuille-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 17.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('MILLE FEUILLES PRALINÉ', 'mille-feuilles-praline', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 13.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('MILLE-FEUILLE', 'mille-feuille', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 12.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('MINI 9 RACHEL', 'mini-9-rachel', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 1.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('MINI BATBOUT FARCI', 'mini-batbout-farci', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 5.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MINI BURGER', 'mini-burger', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 0, NULL, TRUE, TRUE, 30, 48, 'commande', 'unit', NULL, 0, 0),
  ('MINI COOKIES', 'mini-cookies', (SELECT id FROM cat_lookup WHERE slug = 'les-boites'), NULL, 22.5, NULL, TRUE, FALSE, 60, 360, 'dlv', 'unit', NULL, 0, 0),
  ('MINI CROISSANT', 'mini-croissant', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 3.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('MINI MSEMMEN AU KHLII', 'mini-msemmen-au-khlii', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 2.5, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MINI MSEMMEN NATURE', 'mini-msemmen-nature', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 4.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MINI PAIN AU CHOCOLAT', 'mini-pain-au-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 3.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('MINI PAIN AU RAISIN', 'mini-pain-au-raisin', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 3.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('MINI PAIN MAISON', 'mini-pain-maison', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 2.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('MINI PAIN SUISSE', 'mini-pain-suisse', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 3.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('MINI PASTILLA AU POULET', 'mini-pastilla-au-poulet', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MINI PASTILLA AUX FRUITS DE MER', 'mini-pastilla-aux-fruits-de-mer', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 8.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MINI TACOS', 'mini-tacos', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 5.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MSEMEN PRESTIGE', 'msemen-prestige', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 6.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MSEMMEN AU KHLII', 'msemmen-au-khlii', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 8.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MSEMMEN AU OLIVE', 'msemmen-au-olive', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 5.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MUFFIN CARAMEL', 'muffin-caramel', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 0, NULL, TRUE, TRUE, 30, 48, 'commande', 'unit', NULL, 0, 0),
  ('MUFFIN CHOCOLAT', 'muffin-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MUFFIN VANILLE', 'muffin-vanille', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('MUFFINS MINI CHOCOLAT /VANILLE', 'muffins-mini-chocolat-vanille', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 3.5, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('NAVETTE AUX FRAMBOISE', 'navette-aux-framboise', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 7.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('NEMS AU POULET', 'nems-au-poulet', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 8.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('NEMS AUX LEGUMES', 'nems-aux-legumes', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('NOISETTE', 'noisette', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 16.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('NOISETTE 6 PERSONNES (Pâtisserie premium)', 'noisette-6-personnes-patisserie-premium', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 250.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('NOISETTE 6 PERSONNES (Gâteaux & cookies)', 'noisette-6-personnes-gateaux-cookies', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 150.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('NOISETTE 8 PERSONNES', 'noisette-8-personnes', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 300.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('O FAURIA 15 PERSONNES', 'o-fauria-15-personnes', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 350.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('O FAURIA 6 PERSONNES', 'o-fauria-6-personnes', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 150.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('OFAURIA', 'ofauria', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 18.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('OFAURIA 6 PERSONNES', 'ofauria-6-personnes', NULL, NULL, 160.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('OPERA', 'opera', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 15.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('OPERA 6 PERSONNES', 'opera-6-personnes', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 150.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('PAIN AU CHOCOLAT', 'pain-au-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 6.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN AU CHOCOLAT COMPLÈTE', 'pain-au-chocolat-complete', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 7.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN AU CHOCOLAT NOIR', 'pain-au-chocolat-noir', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 6.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN AU RAISIN', 'pain-au-raisin', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 6.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN CHOUFANE', 'pain-choufane', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 6.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN COMPLÈTE', 'pain-complete', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 2.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN COMPLÈTE SANS SEL', 'pain-complete-sans-sel', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 2.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN COPAIN', 'pain-copain', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 6.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN D''ORGE MINI', 'pain-d-orge-mini', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 2.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN DOUBLE CHOCOLAT', 'pain-double-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 7.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN LONG', 'pain-long', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 6.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN MAÏS', 'pain-mais', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 2.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN MAISON', 'pain-maison', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 3.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN NATURE', 'pain-nature', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 1.5, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN O FAURIA', 'pain-o-fauria', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 3.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN O FAURIA MINI', 'pain-o-fauria-mini', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 2.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN ORIENTAL', 'pain-oriental', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 0, NULL, TRUE, TRUE, 2, 24, 'commande', 'unit', NULL, 0, 0),
  ('PAIN SANDWICH COMPLÈTE', 'pain-sandwich-complete', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 1.5, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN SANDWICH NORMALE', 'pain-sandwich-normale', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 1.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN SEMOULE', 'pain-semoule', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 2.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN SUISSE', 'pain-suisse', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 6.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAIN SUISSE NOIR', 'pain-suisse-noir', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 8.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('PAINS AU CHOCOLAT BICOLORES', 'pains-au-chocolat-bicolores', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 8.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('PALMIER SUCRÉ', 'palmier-sucre', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 4.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('PASTILLA AU POULET', 'pastilla-au-poulet', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 15.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PASTILLA AUX FRUITS DE MER', 'pastilla-aux-fruits-de-mer', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 17.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PIZZA CARRÉ AU THON', 'pizza-carre-au-thon', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 8.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PIZZA POULET/THON', 'pizza-poulet-thon', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PIZZA VIANDE HACHÉE', 'pizza-viande-hachee', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 8.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PLATEAU BELDI GRAND', 'plateau-beldi-grand', (SELECT id FROM cat_lookup WHERE slug = 'plateaux'), NULL, 230.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PLATEAU PRESTIGE', 'plateau-prestige', (SELECT id FROM cat_lookup WHERE slug = 'plateaux'), NULL, 250.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PLATEAU PRESTIGE MINI', 'plateau-prestige-mini', (SELECT id FROM cat_lookup WHERE slug = 'plateaux'), NULL, 130.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PLATEAU SABLÉ GRAND', 'plateau-sable-grand', (SELECT id FROM cat_lookup WHERE slug = 'plateaux'), NULL, 150.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PLATEAU SALÉE', 'plateau-salee', (SELECT id FROM cat_lookup WHERE slug = 'plateaux'), NULL, 250.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PLATEAU SOIRÉE', 'plateau-soiree', (SELECT id FROM cat_lookup WHERE slug = 'plateaux'), NULL, 280.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PLATEAU SOIREE MINI', 'plateau-soiree-mini', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 110.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PLATEAU SOIRÉE MINI', 'plateau-soiree-mini-2', (SELECT id FROM cat_lookup WHERE slug = 'plateaux'), NULL, 150.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PLATEAUX MIXTE', 'plateaux-mixte', (SELECT id FROM cat_lookup WHERE slug = 'plateaux'), NULL, 190.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('PRALINO', 'pralino', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 17.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('QRACHEL', 'qrachel', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 3.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('QUICHE AU JAMBON', 'quiche-au-jambon', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('QUICHE AUX CHAMPIGNONS OIGNON CARAMELISE', 'quiche-aux-champignons-oignon-caramelise', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 8.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('QUICHE EPINARD AU FROMAGE', 'quiche-epinard-au-fromage', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('QUICHE SEMON', 'quiche-semon', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 7.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('QUICHE VIANDE HACHÉE', 'quiche-viande-hachee', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 8.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('RED VELVET', 'red-velvet', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 22.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('ROULET CITRON', 'roulet-citron', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 13.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('ROYAL', 'royal', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 19.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('ROYAL 10 PERSONNES', 'royal-10-personnes', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 325.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('ROYAL 10 PERSONNES AVEC PHOTO', 'royal-10-personnes-avec-photo', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 375.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('ROYAL 6 PERSONNES', 'royal-6-personnes', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 160.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('SABLÉ FROMBOISE', 'sable-fromboise', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 3.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('SACHET MADELEINE GRAND', 'sachet-madeleine-grand', (SELECT id FROM cat_lookup WHERE slug = 'les-boites'), NULL, 20.0, NULL, TRUE, FALSE, 60, 360, 'dlv', 'unit', NULL, 0, 0),
  ('SACHET MADELEINE MINI', 'sachet-madeleine-mini', (SELECT id FROM cat_lookup WHERE slug = 'les-boites'), NULL, 15.0, NULL, TRUE, FALSE, 60, 360, 'dlv', 'unit', NULL, 0, 0),
  ('SANDWICH NATURE', 'sandwich-nature', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 1.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('SANDWICH POULET', 'sandwich-poulet', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 18.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('SANDWICH THON', 'sandwich-thon', (SELECT id FROM cat_lookup WHERE slug = 'salee'), NULL, 12.5, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('SANDWICH TRADITION (Pain rond)', 'sandwich-tradition-pain-rond', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 2.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('SANDWICH TRADITION (Baguette tradition)', 'sandwich-tradition-baguette-tradition', (SELECT id FROM cat_lookup WHERE slug = 'baguettes'), NULL, 3.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('TARTE AUX FRUITS', 'tarte-aux-fruits', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 12.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('TARTE BANANE AU CHOCOLAT', 'tarte-banane-au-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 15.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('TARTE CHOCOLAT', 'tarte-chocolat', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 12.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('TARTE CITRON', 'tarte-citron', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 17.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('TARTE FRAMBOISE', 'tarte-framboise', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 12.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('TARTE POMME ET AMANDE', 'tarte-pomme-et-amande', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 15.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('TIGRE GRAND', 'tigre-grand', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 8.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('TIGRE MINI', 'tigre-mini', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 3.5, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('TORSADE', 'torsade', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 3.5, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('TORSADE CHOCOLAT/CRÉME PÂTISSIÈRE', 'torsade-chocolat-creme-patissiere', (SELECT id FROM cat_lookup WHERE slug = 'viennoiseries'), NULL, 7.0, NULL, TRUE, FALSE, 30, 24, 'jour', 'unit', NULL, 0, 0),
  ('TRANCHE CAKE CHOCOLAT/CITRON/NATURE', 'tranche-cake-chocolat-citron-nature', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 5.5, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('TRANCHE CITRON', 'tranche-citron', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 17.0, NULL, TRUE, FALSE, 30, 72, 'dlv', 'unit', NULL, 0, 0),
  ('TRIO', 'trio', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 18.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('TRIO 10 PERSONNES', 'trio-10-personnes', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 280.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('TRIO 6 PERSONNES', 'trio-6-personnes', (SELECT id FROM cat_lookup WHERE slug = 'gateaux'), NULL, 150.0, NULL, TRUE, FALSE, 60, 144, 'dlv', 'unit', NULL, 0, 0),
  ('TROMPE L''OEIL CITRON', 'trompe-l-oeil-citron', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 25.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('TROMPE L''OEIL COCO', 'trompe-l-oeil-coco', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 25.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('TROMPE L''IL FRAMBOISE', 'trompe-l-il-framboise', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 25.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('TROMPE L''IL MANGUE', 'trompe-l-il-mangue', (SELECT id FROM cat_lookup WHERE slug = 'patisseries'), NULL, 25.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'unit', NULL, 0, 0),
  ('VIENNOISES VARIÉS', 'viennoises-varies', (SELECT id FROM cat_lookup WHERE slug = 'pains'), NULL, 2.0, NULL, TRUE, FALSE, 2, 24, 'jour', 'unit', NULL, 0, 0),
  ('HALWAT LOUZ', 'halwat-louz', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 200.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 200.0, 0, 0),
  ('BOULE DE NEIGE', 'boule-de-neige', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 80.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 80.0, 0, 0),
  ('BOULE NESTLÉ COCO', 'boule-nestle-coco', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 125.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 125.0, 0, 0),
  ('BRIOUATE', 'briouate', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 150.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 150.0, 0, 0),
  ('BRIOUATE AMANDE', 'briouate-amande', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 177.5, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 177.5, 0, 0),
  ('COOKIES SPÉCIAL', 'cookies-special', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 132.5, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 132.5, 0, 0),
  ('CORNE DE GAZELLE', 'corne-de-gazelle', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 200.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 200.0, 0, 0),
  ('CORNE DE GAZELLE SÉSAME', 'corne-de-gazelle-sesame', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 200.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 200.0, 0, 0),
  ('FEKASS COMPLÈTE', 'fekass-complete', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 130.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 130.0, 0, 0),
  ('FEKASS COMPLÈTE NOIX', 'fekass-complete-noix', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 175.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 175.0, 0, 0),
  ('FEKKAS COMPLÈTE', 'fekkas-complete', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 130.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 130.0, 0, 0),
  ('FEKKAS RAISIN', 'fekkas-raisin', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 150.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 150.0, 0, 0),
  ('FEKKASS COMPLÈTE', 'fekkass-complete', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 130.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 130.0, 0, 0),
  ('FEKKASS NATURE', 'fekkass-nature', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 120.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 120.0, 0, 0),
  ('FINANCIER ABRICOT', 'financier-abricot', (SELECT id FROM cat_lookup WHERE slug = 'les-boites'), NULL, 200.0, NULL, TRUE, FALSE, 60, 360, 'dlv', 'weight', 200.0, 0, 0),
  ('FINANCIER AUX DATTES', 'financier-aux-dattes', (SELECT id FROM cat_lookup WHERE slug = 'les-boites'), NULL, 200.0, NULL, TRUE, FALSE, 60, 360, 'dlv', 'weight', 200.0, 0, 0),
  ('GHERIBA BAHLA', 'gheriba-bahla', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 120.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 120.0, 0, 0),
  ('GHERIBA CAFÉ', 'gheriba-cafe', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 170.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 170.0, 0, 0),
  ('GHERIBA FROMAGE', 'gheriba-fromage', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 100.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 100.0, 0, 0),
  ('GHRIBA COCO', 'ghriba-coco', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 90.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 90.0, 0, 0),
  ('GHRIBA LOUZA', 'ghriba-louza', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 90.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 90.0, 0, 0),
  ('MAAMOL', 'maamol', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 120.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 120.0, 0, 0),
  ('MAÂMOUL', 'maamoul', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 120.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 120.0, 0, 0),
  ('MAAMOUL', 'maamoul-2', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 120.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 120.0, 0, 0),
  ('MAKROUT', 'makrout', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 100.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 100.0, 0, 0),
  ('MHANCHA AMANDE', 'mhancha-amande', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 200.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 200.0, 0, 0),
  ('NOUGAT CHOCOLAT BLANC', 'nougat-chocolat-blanc', (SELECT id FROM cat_lookup WHERE slug = 'les-boites'), NULL, 75.0, NULL, TRUE, FALSE, 60, 360, 'dlv', 'weight', 75.0, 0, 0),
  ('PLATEAU BELDI', 'plateau-beldi', (SELECT id FROM cat_lookup WHERE slug = 'plateaux'), NULL, 230.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'weight', 230.0, 0, 0),
  ('PLATEAU SABLÉ', 'plateau-sable', (SELECT id FROM cat_lookup WHERE slug = 'plateaux'), NULL, 150.0, NULL, TRUE, FALSE, 30, 48, 'dlv', 'weight', 150.0, 0, 0),
  ('RAFAELLO BALEDI', 'rafaello-baledi', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 125.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 125.0, 0, 0),
  ('RKHAMA AMANDE', 'rkhama-amande', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 200.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 200.0, 0, 0),
  ('SABLÉ', 'sable', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 120.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 120.0, 0, 0),
  ('SABLÉ PRESTIGE', 'sable-prestige', (SELECT id FROM cat_lookup WHERE slug = 'les-boites'), NULL, 125.0, NULL, TRUE, FALSE, 60, 360, 'dlv', 'weight', 125.0, 0, 0),
  ('SHABAKIA', 'shabakia', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 140.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 140.0, 0, 0),
  ('SHABAKIA AMANDE', 'shabakia-amande', (SELECT id FROM cat_lookup WHERE slug = 'beldi'), NULL, 140.0, NULL, TRUE, FALSE, 90, 360, 'dlv', 'weight', 140.0, 0, 0)
ON CONFLICT (slug) DO NOTHING;

COMMIT;
