-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 130 : Fix category_id NULL pour les produits importés en 128
-- 
-- La 128 mappait vers les slugs des migrations historiques (pains, patisseries,
-- gateaux...) qui ont été remplacés dans la DB par les UPPERCASE matching Excel.
-- Cette migration rattache les ~108 produits orphelins à la bonne catégorie en
-- se basant sur leur nom (et donc leur catégorie Excel d'origine).
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- ─── baguette (6 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'baguette')
WHERE category_id IS NULL AND name IN ('BAGUETTE COMPLÈTE', 'BAGUETTE NORMALE', 'BAGUETTE NORMALE 1,25', 'BAGUETTE NORMALE FARINE', 'BAGUETTE NORMALE SÉSAME', 'BAGUETTE SEMOULE');

-- ─── baguette-tradition (10 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'baguette-tradition')
WHERE category_id IS NULL AND name IN ('BAGUETTE AVOINE (CHOFANE)', 'BAGUETTE TRADITION CÉRÉALE', 'BAGUETTE TRADITION OLIVE', 'BAGUETTE TRADITION PAVOT', 'BAGUETTE TRADITION SÉSAME', 'BAGUETTE À L''ANCIENNE', 'PAIN CHOUFANE', 'PAIN COPAIN', 'PAIN LONG', 'SANDWICH TRADITION (Baguette tradition)');

-- ─── beldi (35 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'beldi')
WHERE category_id IS NULL AND name IN ('BAGHRIR 10 PIÈCES', 'BATBOUT', 'BOULE DE NEIGE', 'BOULE NESTLÉ COCO', 'BRIOUATE', 'BRIOUATE AMANDE', 'COOKIES SPÉCIAL', 'CORNE DE GAZELLE', 'CORNE DE GAZELLE SÉSAME', 'FEKASS COMPLÈTE', 'FEKASS COMPLÈTE NOIX', 'FEKKAS COMPLÈTE', 'FEKKAS CRÈME', 'FEKKAS RAISIN', 'FEKKASS COMPLÈTE', 'FEKKASS NATURE', 'FEUILLETINE FROMAGE', 'GHERIBA BAHLA', 'GHERIBA CAFÉ', 'GHERIBA FROMAGE', 'GHRIBA COCO', 'GHRIBA LOUZA', 'GHRIBA NATURE', 'HALWAT LOUZ', 'LE RESTE DU COMMANDE GÂTEAU BELDI', 'MAAMOL', 'MAAMOUL', 'MAKROUT', 'MAÂMOUL', 'MHANCHA AMANDE', 'RAFAELLO BALEDI', 'RKHAMA AMANDE', 'SABLÉ', 'SHABAKIA', 'SHABAKIA AMANDE');

-- ─── gateaux-cookies (29 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'gateaux-cookies')
WHERE category_id IS NULL AND name IN ('AMANDINE 8 PERSONNES', 'CAKE CHOCOLAT', 'CAKE CITRON', 'CAKE DESIGN', 'CAKE FRUITS SECS', 'CAKE NATURE', 'CAKE ROCHER CHOCOLAT', 'CAKE ROCHER FRAMBOISE', 'CAKE ROCHER FRUITS SECS', 'CASABLANCA 10 PERSONNES', 'CASABLANCA 6 PERSONNE', 'COOKIES CHOCOLAT', 'COOKIES FRAMBOISE', 'COOKIES PISTACHE', 'FEUILLE 8 PERSONNES', 'FRAISIER 15 PERSONNES', 'GÂTEAU FRUITS 8 PERSONNES', 'GÂTEAU O FAURIA 15 PERS', 'GÂTEAUX FERRERO ROCHER 10 PIÈCES', 'NOISETTE 6 PERSONNES (Gâteaux & cookies)', 'O FAURIA 15 PERSONNES', 'O FAURIA 6 PERSONNES', 'OPERA 6 PERSONNES', 'ROYAL 10 PERSONNES', 'ROYAL 10 PERSONNES AVEC PHOTO', 'ROYAL 6 PERSONNES', 'TRANCHE CAKE CHOCOLAT/CITRON/NATURE', 'TRIO 10 PERSONNES', 'TRIO 6 PERSONNES');

-- ─── les-boites (9 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'les-boites')
WHERE category_id IS NULL AND name IN ('BOÎTE SALÉE', 'DIAMANTINE FROMAGE', 'DIAMANTINE NATURE', 'FEKASS DENTELLE', 'FINANCIER ABRICOT', 'FINANCIER AUX DATTES', 'MINI COOKIES', 'NOUGAT CHOCOLAT BLANC', 'SABLÉ PRESTIGE');

-- ─── macaron (6 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'macaron')
WHERE category_id IS NULL AND name IN ('MACARON', 'MACARON CHOCOLAT', 'MACARON CITRON', 'MACARON FRAMBOISE', 'MACARON PISTACHE', 'MACARON VANILLE');

-- ─── pain-rond (15 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'pain-rond')
WHERE category_id IS NULL AND name IN ('MINI PAIN MAISON', 'PAIN COMPLÈTE', 'PAIN COMPLÈTE SANS SEL', 'PAIN D''ORGE MINI', 'PAIN MAISON', 'PAIN MAÏS', 'PAIN NATURE', 'PAIN O FAURIA', 'PAIN O FAURIA MINI', 'PAIN ORIENTAL', 'PAIN SANDWICH COMPLÈTE', 'PAIN SANDWICH NORMALE', 'PAIN SEMOULE', 'SANDWICH TRADITION (Pain rond)', 'VIENNOISES VARIÉS');

-- ─── pain-sandwich (1 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'pain-sandwich')
WHERE category_id IS NULL AND name IN ('SANDWICH NATURE');

-- ─── patisserie-classique (18 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'patisserie-classique')
WHERE category_id IS NULL AND name IN ('CAKE CAROTTE', 'CAKE OREO', 'CAKE ROCHER TRANCHE', 'ECLAIR CHOCOLAT', 'ECLAIR FRAMBOISE', 'ECLAIR VANILLE', 'FRAISIER', 'GATEAUX MOELLEUX', 'MACARON 6 PS', 'MILLE FEUILLE CHOCOLAT', 'MILLE FEUILLES PRALINÉ', 'MILLE-FEUILLE', 'ROULET CITRON', 'TARTE AUX FRUITS', 'TARTE CHOCOLAT', 'TARTE CITRON', 'TARTE FRAMBOISE', 'TRANCHE CITRON');

-- ─── patisserie-premium (25 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'patisserie-premium')
WHERE category_id IS NULL AND name IN ('AMANDINE', 'AMANDINE 6 PERSONNES', 'CASABLANCA', 'CHEESECAKE CITRON', 'CHEESECAKE FRAMBOISE', 'CHEESECAKE LOTUS', 'CRUNCHE CARAMEL', 'FEUILLES D''AUTOMNE 8 PERSONNES', 'FORÊT NOIR', 'NOISETTE', 'NOISETTE 6 PERSONNES (Pâtisserie premium)', 'NOISETTE 8 PERSONNES', 'OFAURIA', 'OPERA', 'PRALINO', 'RED VELVET', 'ROYAL', 'TARTE BANANE AU CHOCOLAT', 'TARTE POMME ET AMANDE', 'TRIO', 'TROMPE L''IL FRAMBOISE', 'TROMPE L''IL MANGUE', 'TROMPE L''OEIL CITRON', 'TROMPE L''OEIL COCO', 'ÉCLAIRE FRAISE');

-- ─── pieces-portions (13 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'pieces-portions')
WHERE category_id IS NULL AND name IN ('BROWNIE', 'CASABLANCA 8 PERSONNES', 'FINANCIER GRAND', 'FINANCIER MINI', 'MADELEINE', 'MADELEINE CHOCOLAT', 'MADELEINE CITRON', 'MUFFIN CARAMEL', 'MUFFIN CHOCOLAT (Pièces & portions)', 'MUFFIN VANILLE (Pièces & portions)', 'MUFFINS MINI CHOCOLAT /VANILLE', 'TIGRE GRAND', 'TIGRE MINI');

-- ─── plateau-sale-sucre (12 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'plateau-sale-sucre')
WHERE category_id IS NULL AND name IN ('LE RESTE DU COMMANDE PLATEAU SOIRÉE G', 'LE RESTE DU PLATEAU SOIRÉE G', 'PLATEAU BELDI', 'PLATEAU BELDI GRAND', 'PLATEAU PRESTIGE', 'PLATEAU PRESTIGE MINI', 'PLATEAU SABLÉ', 'PLATEAU SABLÉ GRAND', 'PLATEAU SALÉE', 'PLATEAU SOIRÉE', 'PLATEAU SOIRÉE MINI', 'PLATEAUX MIXTE');

-- ─── sachet-mini (2 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'sachet-mini')
WHERE category_id IS NULL AND name IN ('SACHET MADELEINE GRAND', 'SACHET MADELEINE MINI');

-- ─── sale (46 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'sale')
WHERE category_id IS NULL AND name IN ('BASBOUSA', 'BASBOUSA CRÈME', 'BATBOUT MINI', 'BEBE BATBOUT 1 PIECE', 'BEBE BATBOUT 10 PIÈCES', 'BEBE MSEMEN FARCI VIANDE', 'BEBE SANDWICH COMPLÈTE', 'BRIOUATE POULET', 'BRIOUATE VIANDE HACHÉE', 'CHAHDA', 'CROC MONSIEUR', 'CROC MONSIEUR MINI', 'CROISSANT SALÉE', 'HARCHA COMPLÈTE', 'HARCHA KOUNAFA', 'HARCHA ORGE', 'HARCHA RAISIN', 'HARSHA', 'HARSHA FROMAGE', 'HARSHA OLIVE', 'KOUNAFA CREME', 'MINI BATBOUT FARCI', 'MINI BURGER', 'MINI MSEMMEN AU KHLII', 'MINI MSEMMEN NATURE', 'MINI PASTILLA AU POULET', 'MINI PASTILLA AUX FRUITS DE MER', 'MINI TACOS', 'MSEMEN PRESTIGE', 'MSEMMEN AU KHLII', 'MSEMMEN AU OLIVE', 'NEMS AU POULET', 'NEMS AUX LEGUMES', 'PASTILLA AU POULET', 'PASTILLA AUX FRUITS DE MER', 'PIZZA CARRÉ AU THON', 'PIZZA POULET/THON', 'PIZZA VIANDE HACHÉE', 'QUICHE AU JAMBON', 'QUICHE AUX CHAMPIGNONS OIGNON CARAMELISE', 'QUICHE EPINARD AU FROMAGE', 'QUICHE SEMON', 'QUICHE VIANDE HACHÉE', 'SABLÉ FROMBOISE', 'SANDWICH POULET', 'SANDWICH THON');

-- ─── sale-soiree (1 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'sale-soiree')
WHERE category_id IS NULL AND name IN ('PLATEAU SOIREE MINI');

-- ─── viennoiseries (41 produits) ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'viennoiseries')
WHERE category_id IS NULL AND name IN ('BAGUETTE SUCRÉE', 'BEIGNETS', 'BEIGNETS CHOCOLAT/CITRON/FRAMBOISE', 'BOSTOCK AMANDE', 'BRIOCHE', 'CHAUSSON AUX POMMES', 'CROISSANT', 'CROISSANT AMÉRICAIN', 'CROISSANT AU CHOCOLAT NOIR', 'CROISSANT BICOLORE CACAO', 'CROISSANT COMPLÈTE', 'DANISH ABRICOT', 'DANISH CHOCOLAT', 'DANISH FRAMBOISE/CHOCOLAT', 'DANISH FRUITS', 'FLAN VANILLE', 'FOURRÉ AMANDE G', 'FOURRÉ AMANDE/CHOCOLAT/CITRON', 'JALOUSIE ABRICOT', 'JALOUSIE AUX AMANDES', 'JALOUSIE AUX POMMES', 'JALOUSIE ROND POMME', 'LE RESTE DU PLATEAU VIENNOISERIES', 'MINI 9 RACHEL', 'MINI CROISSANT', 'MINI PAIN AU CHOCOLAT', 'MINI PAIN AU RAISIN', 'MINI PAIN SUISSE', 'NAVETTE AUX FRAMBOISE', 'PAIN AU CHOCOLAT', 'PAIN AU CHOCOLAT COMPLÈTE', 'PAIN AU CHOCOLAT NOIR', 'PAIN AU RAISIN', 'PAIN DOUBLE CHOCOLAT', 'PAIN SUISSE', 'PAIN SUISSE NOIR', 'PAINS AU CHOCOLAT BICOLORES', 'PALMIER SUCRÉ', 'QRACHEL', 'TORSADE', 'TORSADE CHOCOLAT/CRÉME PÂTISSIÈRE');

-- ─── Produits sans catégorie Excel (NaN) — inférence par produit similaire ───
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'patisserie-premium')
WHERE category_id IS NULL AND name IN ('FEUILLE D''AUTOMNE', 'OFAURIA 6 PERSONNES');
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'pieces-portions')
WHERE category_id IS NULL AND name IN ('MUFFIN CHOCOLAT', 'MUFFIN VANILLE');

-- Garde-fou : alerte si des produits restent sans catégorie
DO $$
DECLARE orphans INT;
BEGIN
  SELECT COUNT(*) INTO orphans FROM products WHERE category_id IS NULL;
  IF orphans > 0 THEN
    RAISE WARNING '% produit(s) restent sans catégorie après cleanup', orphans;
  END IF;
END $$;

COMMIT;